#!/usr/bin/env node
// Generates frontend/public/js/env.js from environment variables.
// Run: node scripts/generate-env.js
// Set env vars before running, or place them in a root .env file.

const fs = require("fs");
const path = require("path");

// Load root .env if present
const rootEnv = path.join(__dirname, "../.env");
if (fs.existsSync(rootEnv)) {
  require("fs").readFileSync(rootEnv, "utf8").split("\n").forEach(line => {
    const [k, ...v] = line.split("=");
    if (k && v.length && !process.env[k.trim()]) {
      process.env[k.trim()] = v.join("=").trim();
    }
  });
}

const SUPABASE_URL     = process.env.SUPABASE_URL;
const SUPABASE_ANON    = process.env.SUPABASE_ANON_KEY;
const BACKEND_URL      = process.env.BACKEND_URL || "";
const STORAGE_PROVIDER = process.env.STORAGE_PROVIDER || "supabase";
const STORJ_UPLOAD_URL = process.env.STORJ_UPLOAD_URL || "";

if (!SUPABASE_URL || !SUPABASE_ANON) {
  console.error("ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set.");
  process.exit(1);
}

const out = `// Auto-generated by scripts/generate-env.js — DO NOT COMMIT
window.WINZO_ENV = {
  SUPABASE_URL:     "${SUPABASE_URL}",
  SUPABASE_ANON:    "${SUPABASE_ANON}",
  STORAGE_PROVIDER: "${STORAGE_PROVIDER}",
  STORJ_UPLOAD_URL: "${STORJ_UPLOAD_URL}",
};
`;

const dest = path.join(__dirname, "../frontend/public/js/env.js");
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log("✓ env.js generated.");
